version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.17.0
    ports:
      - 8080:8080
    restart: always
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTOSCHEMA_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
    volumes:
      - weaviate-data:/var/lib/weaviate
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilroberta-base-v2
    environment:
      ENABLE_CUDA: 0
      NVIDIA_VISIBLE_DEVICES: all
    restart: always
    deploy:
          resources:
            reservations:
              devices:
                - capabilities: [gpu] 
volumes:
  weaviate-data:
